/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDataRouteImport } from './routes/api.data'
import { Route as ApiBadgeRouteImport } from './routes/api.badge'
import { Route as AdminMonitorsRouteImport } from './routes/admin.monitors'
import { Route as ApiAdminMonitorsRouteImport } from './routes/api.admin.monitors'
import { Route as ApiAdminMonitorsReorderRouteImport } from './routes/api.admin.monitors.reorder'
import { Route as ApiAdminMonitorsImportRouteImport } from './routes/api.admin.monitors.import'
import { Route as ApiAdminMonitorsIdRouteImport } from './routes/api.admin.monitors.$id'

const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgeRoute = ApiBadgeRouteImport.update({
  id: '/api/badge',
  path: '/api/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitorsRoute = AdminMonitorsRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminMonitorsRoute = ApiAdminMonitorsRouteImport.update({
  id: '/api/admin/monitors',
  path: '/api/admin/monitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMonitorsReorderRoute = ApiAdminMonitorsReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => ApiAdminMonitorsRoute,
} as any)
const ApiAdminMonitorsImportRoute = ApiAdminMonitorsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiAdminMonitorsRoute,
} as any)
const ApiAdminMonitorsIdRoute = ApiAdminMonitorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminMonitorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/incidents': typeof IncidentsRoute
  '/admin/monitors': typeof AdminMonitorsRoute
  '/api/badge': typeof ApiBadgeRoute
  '/api/data': typeof ApiDataRoute
  '/api/admin/monitors': typeof ApiAdminMonitorsRouteWithChildren
  '/api/admin/monitors/$id': typeof ApiAdminMonitorsIdRoute
  '/api/admin/monitors/import': typeof ApiAdminMonitorsImportRoute
  '/api/admin/monitors/reorder': typeof ApiAdminMonitorsReorderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/incidents': typeof IncidentsRoute
  '/admin/monitors': typeof AdminMonitorsRoute
  '/api/badge': typeof ApiBadgeRoute
  '/api/data': typeof ApiDataRoute
  '/api/admin/monitors': typeof ApiAdminMonitorsRouteWithChildren
  '/api/admin/monitors/$id': typeof ApiAdminMonitorsIdRoute
  '/api/admin/monitors/import': typeof ApiAdminMonitorsImportRoute
  '/api/admin/monitors/reorder': typeof ApiAdminMonitorsReorderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/incidents': typeof IncidentsRoute
  '/admin/monitors': typeof AdminMonitorsRoute
  '/api/badge': typeof ApiBadgeRoute
  '/api/data': typeof ApiDataRoute
  '/api/admin/monitors': typeof ApiAdminMonitorsRouteWithChildren
  '/api/admin/monitors/$id': typeof ApiAdminMonitorsIdRoute
  '/api/admin/monitors/import': typeof ApiAdminMonitorsImportRoute
  '/api/admin/monitors/reorder': typeof ApiAdminMonitorsReorderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/incidents'
    | '/admin/monitors'
    | '/api/badge'
    | '/api/data'
    | '/api/admin/monitors'
    | '/api/admin/monitors/$id'
    | '/api/admin/monitors/import'
    | '/api/admin/monitors/reorder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/incidents'
    | '/admin/monitors'
    | '/api/badge'
    | '/api/data'
    | '/api/admin/monitors'
    | '/api/admin/monitors/$id'
    | '/api/admin/monitors/import'
    | '/api/admin/monitors/reorder'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/incidents'
    | '/admin/monitors'
    | '/api/badge'
    | '/api/data'
    | '/api/admin/monitors'
    | '/api/admin/monitors/$id'
    | '/api/admin/monitors/import'
    | '/api/admin/monitors/reorder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  IncidentsRoute: typeof IncidentsRoute
  ApiBadgeRoute: typeof ApiBadgeRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiAdminMonitorsRoute: typeof ApiAdminMonitorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badge': {
      id: '/api/badge'
      path: '/api/badge'
      fullPath: '/api/badge'
      preLoaderRoute: typeof ApiBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitors': {
      id: '/admin/monitors'
      path: '/monitors'
      fullPath: '/admin/monitors'
      preLoaderRoute: typeof AdminMonitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/monitors': {
      id: '/api/admin/monitors'
      path: '/api/admin/monitors'
      fullPath: '/api/admin/monitors'
      preLoaderRoute: typeof ApiAdminMonitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/monitors/reorder': {
      id: '/api/admin/monitors/reorder'
      path: '/reorder'
      fullPath: '/api/admin/monitors/reorder'
      preLoaderRoute: typeof ApiAdminMonitorsReorderRouteImport
      parentRoute: typeof ApiAdminMonitorsRoute
    }
    '/api/admin/monitors/import': {
      id: '/api/admin/monitors/import'
      path: '/import'
      fullPath: '/api/admin/monitors/import'
      preLoaderRoute: typeof ApiAdminMonitorsImportRouteImport
      parentRoute: typeof ApiAdminMonitorsRoute
    }
    '/api/admin/monitors/$id': {
      id: '/api/admin/monitors/$id'
      path: '/$id'
      fullPath: '/api/admin/monitors/$id'
      preLoaderRoute: typeof ApiAdminMonitorsIdRouteImport
      parentRoute: typeof ApiAdminMonitorsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMonitorsRoute: typeof AdminMonitorsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMonitorsRoute: AdminMonitorsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAdminMonitorsRouteChildren {
  ApiAdminMonitorsIdRoute: typeof ApiAdminMonitorsIdRoute
  ApiAdminMonitorsImportRoute: typeof ApiAdminMonitorsImportRoute
  ApiAdminMonitorsReorderRoute: typeof ApiAdminMonitorsReorderRoute
}

const ApiAdminMonitorsRouteChildren: ApiAdminMonitorsRouteChildren = {
  ApiAdminMonitorsIdRoute: ApiAdminMonitorsIdRoute,
  ApiAdminMonitorsImportRoute: ApiAdminMonitorsImportRoute,
  ApiAdminMonitorsReorderRoute: ApiAdminMonitorsReorderRoute,
}

const ApiAdminMonitorsRouteWithChildren =
  ApiAdminMonitorsRoute._addFileChildren(ApiAdminMonitorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  IncidentsRoute: IncidentsRoute,
  ApiBadgeRoute: ApiBadgeRoute,
  ApiDataRoute: ApiDataRoute,
  ApiAdminMonitorsRoute: ApiAdminMonitorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
